# Generated by Django 4.2.6 on 2023-11-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existingPath', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('eof', models.BooleanField()),
            ],
        ),
    ]
