# Generated by Django 4.2.6 on 2023-11-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationalID', models.CharField(max_length=11)),
                ('emailAdd', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
